name: 'Run Dash Platform Test Suite'
description: 'Runs end-to-end and functional testing against a Dash network'
inputs:
  sdk-install:
    description: SDK install
  faucet-private-key:
    description: Faucet private key
  dpns-contract-id:
    description: DPNS contract ID
  dpns-top-level-identity-id:
    description: DPNS top level identity ID
  dpns-top-level-identity-private-key:
    description: DPNS top level identity private key
  platform-test-suite-branch:
    description: Platform Test Suite version
    default: latest
runs:
  using: composite
  steps:
    - name: Start local network
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        source bin/run-platform-test-suite.sh \
        --scope=platform \
        --network=regtest \
        --npm-install=${{ inputs.sdk-install }} \
        --faucet-key=${{ inputs.faucet-private-key }} \
        --dpns-contract-id=${{ inputs.dpns-contract-id }} \
        --dpns-tld-identity-id=${{ inputs.dpns-top-level-identity-id }} \
        --dpns-tld-identity-private-key=${{ inputs.dpns-top-level-identity-private-key }}
