name: 'Run Dash Platform Test Suite'
description: 'Runs end-to-end and functional testing against a Dash network'
inputs:
  sdk-branch:
    description: SDK branch to install
  faucet-private-key:
    description: Faucet private key
  dpns-contract-id:
    description: DPNS contract ID
  dpns-top-level-identity-id:
    description: DPNS top level identity ID
  dpns-top-level-identity-private-key:
    description: DPNS top level identity private key
  feature-flags-identity-id:
    description: Feature flags identity ID
  feature-flags-contract-id:
    description: Feature flags contract ID
  platform-test-suite-branch:
    description: Platform Test Suite version
    default: master
  scope:
    description: Platform Test Suite scope
runs:
  using: composite
  steps:
    - name: Tmp dir
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "TMPDIR=/tmp" >> $GITHUB_ENV

    - name: Clone repository
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        git clone --depth 1 --branch ${{ inputs.platform-test-suite-branch }} https://github.com/dashevo/platform-test-suite.git "${{ env.TMPDIR }}/platform-test-suite"

    - name: Install dependencies
      shell: bash
      working-directory: "${{ env.TMPDIR }}/platform-test-suite"
      run: |
        npm ci

    - name: Start local network
      shell: bash
      working-directory: "${{ env.TMPDIR }}/platform-test-suite"
      run: |
        source bin/test.sh 127.0.0.1:3000:3010 \
        --npm-install=github:dashevo/js-dash-sdk#${{ inputs.sdk-branch }} \
        --scope=${{ inputs.scope }} \
        --network=regtest \
        --faucet-key=${{ inputs.faucet-private-key }} \
        --dpns-contract-id=${{ inputs.dpns-contract-id }} \
        --dpns-tld-identity-id=${{ inputs.dpns-top-level-identity-id }} \
        --dpns-tld-identity-private-key=${{ inputs.dpns-top-level-identity-private-key }} \
        --feature-flags-identity-id=${{ inputs.feature-flags-identity-id }} \
        --feature-flags-contract-id=${{ inputs.feature-flags-contract-id }}
